name: M2 - Extension Manual
on:
  workflow_dispatch:
      inputs:
        MAGENTO_VERSION:
          default: ''
          required: false
          type: string
        CREATE_RELEASE:
          type: boolean
          required: false
          default: false
  
jobs:
  magento2-extension:
    uses: fooman/fm0153_workflows/.github/workflows/fooman-m2.yml@main
    secrets: inherit
    with:
      MAGENTO_VERSION: ${{ inputs.MAGENTO_VERSION }}
      CREATE_RELEASE: ${{ inputs.CREATE_RELEASE }}
